# Google Cloud Build設定
# WorldSpeak AI自動デプロイ用

steps:
  # Docker imageをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/worldspeak-ai:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/worldspeak-ai:latest'
      - '.'

  # Container Registryにpush
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/worldspeak-ai:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/worldspeak-ai:latest'

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'worldspeak-ai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/worldspeak-ai:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# ビルドオプション
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# タイムアウト設定
timeout: '1200s'

# 置換変数
substitutions:
  _DEPLOY_REGION: 'asia-northeast1'

# CloudBuildのログ保存
logsBucket: 'gs://${PROJECT_ID}-cloudbuild-logs'